### ISSUE TITLE
Support (number of photos, customize buttons)

### ISSUE THREAD

**Issue by anirudhamahale** [pantuspavel/PPAssetsActionController#31]
I am using your library and it's very good, thanks for source code.
I would like to request you to add things like 
1) Maximum number of photos or media that we can select
2) Customize the default button i.e Snap Image or Video and send x items
3) Update the documentation on how to call the delegate methods on the PPOption buttons
`let option = PPOption(withTitle: "Pick Image") { 
            // I want to call assetsPicker(_ picker: PPAssetsActionController, didFinishPicking assets: [MediaProvider]) method on click of this button
        }`

This is what I found should be added.

**Comment by pavelpantus** [comment]
Hey, @anirudhamahale , thank you for your feedback! Greatly appreciated!
I'll file separate issues for each of you request to track them separately when I have a chance.

To clarify on point 3: do you want `PPAssetsActionController` to call you back when one of the options was selected? If so, I'd go with a new `PPAssetsActionControllerDelegate` method, something like:
```obj-c
func assetsPicker(_ picker: PPAssetsActionController, didPickOption option: PPOption);
```
Let me know what you think, thanks!

**Comment by pavelpantus** [comment]
Closing in favor of #32 #33 #34 
I encourage you to take a stab at any of it without waiting my implementation.
Just communicate in the ticket that you're interested in implementing a feature, so I'd know and we avoid implementing the same feature twice.
Thanks again for filing the ticket @anirudhamahale
