### ISSUE TITLE
Update project for Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by vitalrum** [pantuspavel/PPAssetsActionController#35]
Hi, will you update your project?

**Comment by pavelpantus** [comment]
Hey Vitaly,
Thanks for your request!
I'll try to tackle this one as soon as possible -- nothing worse then outdated dependency.
In the meantime PRs are welcome. If you'll decide to help, please communicate it here. 👍

**Comment by pavelpantus** [comment]
@vitalrum please update to [0.3.2](https://github.com/pantuspavel/PPAssetsActionController/releases/tag/0.3.2).
Create a new issue if you encounter any problem.

**Comment by vitalrum** [comment]
thanks!
